--
-- PostgreSQL database dump
--

-- Dumped from database version 13.8
-- Dumped by pg_dump version 13.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: book; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book (
    id_book integer NOT NULL,
    id_person integer,
    name_of_book character varying NOT NULL,
    date_of_writing character varying,
    author character varying NOT NULL,
    taken_at timestamp without time zone,
    img_url character varying
);


ALTER TABLE public.book OWNER TO postgres;

--
-- Name: book_id_book_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.book ALTER COLUMN id_book ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_id_book_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: person; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.person (
    id_person integer NOT NULL,
    name character varying(100) NOT NULL,
    year_of_birth integer,
    username character varying NOT NULL,
    password character varying NOT NULL,
    role character varying,
    activation_code character varying,
    registration_at timestamp without time zone,
    CONSTRAINT person_age_check CHECK ((year_of_birth > 0))
);


ALTER TABLE public.person OWNER TO postgres;

--
-- Name: person_id_person_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.person ALTER COLUMN id_person ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_id_person_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: book; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.book (id_book, id_person, name_of_book, date_of_writing, author, taken_at, img_url) FROM stdin;
39	16	Тайные виды на гору Фудзи	2016	Виктор Пелевин	2022-12-15 21:26:22.362	/images/fudjiPelevin.png
96	\N	Евангелие	1	Иисус из Назарета	\N	/images/c0f32761-9f1b-4e88-bc43-c9078757aaeb.1024942794.jpg
40	\N	Бесы	1870	Федор Михайлович Достаевский 	2022-12-15 21:50:16.236	/images/demons.jpg
60	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
42	\N	Сказка о золотой рыбке	1710	Пушкин Александр Сергеевич	2023-01-22 23:44:46.78	/images/storyOfGoldFish.jpg
65	55	Роман	2014	Владимир Сорокин	2023-02-10 22:59:32.136	/images/7ca44a79-395c-4eba-8f80-cde602e8151b.vladimir_sorokin_roman.jpg
41	55	Тайные виды на гору Фудзи	333	Платон	2023-02-10 23:05:29.489	/images/gosudarstvoPlaton.jpeg
97	55	Отцы и дети	1850	Тургенев	2023-02-10 23:05:36.04	/images/99e19200-bd7c-44d3-9ffa-288ac246efa9.3a15cade-2970-4f17-b8e8-988c446217e1.jpg
61	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
63	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
64	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
66	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
67	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
68	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
69	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
70	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
71	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
72	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
73	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
74	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
75	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
76	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
77	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
78	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
79	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
80	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
81	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
82	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
83	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
84	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
85	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
86	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
87	\N	Test	2000	Dostaevski	2023-01-25 00:00:00	/images/demons.jpg
93	\N	Братья Карамазовы	1880	Доставеский	\N	/images/3c213618-61ae-480b-934a-e2778b10145f.cover1__w340 (1).jpg
\.


--
-- Data for Name: person; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.person (id_person, name, year_of_birth, username, password, role, activation_code, registration_at) FROM stdin;
47	Петров Дмитрий Петрович	1988	pet@mail.ru	$2a$10$qLDfN62K5aUwCzh9zBJ5EucQFR.7kZf578x851kyoO6YBb3.im2bO	ROLE_USER	\N	\N
17	Орлов Петр Викторович	2002	orlov@mail.ru	$2a$10$Ak1dR0Xcc1nsQJcG.eh5bOwcYwHa14YL0aV3r0GbvexBvhUrC75ka	ROLE_USER	\N	\N
48	Степанова Наталья Илинична	1966	step@mail.ru	$2a$10$Ny0F7zj3UqwMpwmmuiPUjO8jgihCzAPMXm0/rn4Pk6nLElJVEmXwS	ROLE_USER	\N	\N
49	Егоров Сергей Дмитриевич	2002	stex9800@yandex.ru	$2a$10$1NOqQYCMyv9cJ9BB6/at7ewVIXHGDm7v8pMCOJZDG/QP/fnPnb0d6	ROLE_USER	\N	\N
51	Савин Ярослав Владимирович	2016	yariksavin@gmail.com	$2a$10$dtojtv3vuAtuhjL.sDjrNOhp06Y9d8fGzc6B2lopzRj3ffDt8udw6	ROLE_USER	\N	\N
16	Самарин Илья Андреевич	2002	sx98@mail.ru	$2a$10$yNKTWIEu4lMSR7ecjQJZVOpzmsbxE54flB8/6MoVFvrE3LKbbuLU.	ROLE_ADMIN	\N	\N
52	Алексеев Андрей Михайлович	2002	alekseev@gmail.com	$2a$10$1SakIdgxXqGDrlUwWCBUNO17CTS8NNmanIKZ/q1HY0sqVRyFx1HUS	ROLE_USER	\N	\N
53	Степанов Константин Викторович	1978	kostik@gmail.com	$2a$10$hksbBbpphXWU111gUZ0QjuBOHgZs4dOa22ZnV1Jp6XFR0RyTmhNP6	ROLE_USER	\N	\N
54	Савин Владимир Николаевич	1975	vova@gmail.com	$2a$10$sIURI6CKFr/WRa3Vb2j5XuL4zLr0w9L6CTtW47G3r.pgfAp4ioKA2	ROLE_USER	\N	\N
55	Немцов Георгий Геннадиевич	1977	nemtsov@gmail.com	$2a$10$/VTPn4IxkIoEbF7569THTu.5AclBqaeCP94joKe2dz7zlZgRdGyE.	ROLE_USER	\N	\N
46	Даниил Идзуми	2001	d@mail.ru	$2a$10$lU5juxXtgrJCIjz.lTwabuD75mZfVCLzTAoiJaZ.PTxZRasJm0Pea	ROLE_USER	\N	\N
56	Егоров Сергей Дмитриевич	2002	stex9800@mail.ru	$2a$10$ap1kaLEp/M7rpgYDFAtK8.rTa28Wl4MOcLzNZsuyqdcBQmkFtDke.	ROLE_USER	\N	2023-02-10 20:41:24.484
20	Гурин Владислав Ильич	2002	g@mail.ru	$2a$10$S0qybnX9fgZRg0T6qU7Jaen2TTqtSgo2XokmPW8DOd5ryLwZHVj/2	ROLE_USER	\N	\N
44	Ставрогин Николай Вседолович	1900	zeavs9800@gmail.com	$2a$10$0q86dquGK6n/1a/FzUQacuBJcy2H6j8mCWDSM83DiSDbTOj6oyQ.6	ROLE_ADMIN	\N	\N
\.


--
-- Name: book_id_book_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.book_id_book_seq', 104, true);


--
-- Name: person_id_person_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.person_id_person_seq', 57, true);


--
-- Name: book book_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_pkey PRIMARY KEY (id_book);


--
-- Name: person person_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_email_key UNIQUE (username);


--
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id_person);


--
-- Name: book id_book_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT id_book_fk FOREIGN KEY (id_person) REFERENCES public.person(id_person) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

